<?php
	// Determine progress step
	$progressStep = 10;
	// Determine progress
	if (isset($this->progress) && $this->progress > 0)
		$progress = (int) $this->progress;
	else
		$progress = 0;
	// Add META refresh for browsers without Javascript support
	// @var \Zend\View\Helper\HeadMeta
	$this->headMeta()->appendHttpEquiv('Refresh', '2; URL=' . $this->url('feed-read') . '?progress=' . (string) $this->progress);
?>
<h1>Reading feed</h1>
<p class="progress-percentage" href="<?php echo $this->url('feed-read'); ?>">
	<?php for ($progressCount = 0; $progressCount < $this->progress ; $progressCount += $progressStep) { ?>
		<?php printf('%d', $progressCount); ?>% .. 
	<?php } ?>
	<?php echo $this->progress; ?>%
</p>